[project]
name = "banana-prediction-cnn"
version = "0.1.0"
description = "Project to predict banana ripeness level"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
